const gambar = require('./gambar.png')
const pictsea = require('./pictsea.png')
const kategioriHewan = require('./hewan-kategori.png')
const halfCircle = require('./Ellipselingkaran.png')
const logindulu = require('./logindulu.png')
const downloadIcon = require('./download-icon.png')
const abstrakKategori = require('./abstrak-kategori.png')
const hewanRusa = require('./hewanRusa-kategori.png')
const galaxy = require('./galaxy.png')
const kotaKategori = require('./kota-kategori.png')
const musimKategori = require('./musim-kategori.png')
const tumbuhanKategori = require('./tumbuhanKategori.png')
const dana = require('./dana.png')
const gopay = require('./gopay.png')
const shope = require('./shope.png')
const ovo = require('./ovo.png')

export const images = { dana, ovo, gopay, shope, galaxy, musimKategori, tumbuhanKategori, hewanRusa, kotaKategori, abstrakKategori, downloadIcon, gambar, pictsea, kategioriHewan, halfCircle, logindulu }